# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: main

jobs:
    check:
        name: Test

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        outputs:
            source_any_changed: ${{ steps.changed-files.outputs.any_changed }}

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Check changed files
              id: changed-files
              uses: tj-actions/changed-files@v35.6.3
              with:
                  files: |
                      src/**
                      types/**

            - name: Display is any source files changed
              run: echo ${{ steps.changed-files.outputs.any_changed == 'true' }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run CI
              run: npm run ci

    publish:
        name: Publish

        needs: check

        if: ${{ success() && github.repository_owner == 'dirain1700' && needs.check.outputs.source_any_changed }}

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: "https://registry.npmjs.org"
                  scope: "@dirain"
                  always-auth: true

            - name: Install dependencies
              run: npm ci

            - name: Update package version
              run: npm version prerelease --preid "dev.$(date +%s)-$(git rev-parse --short HEAD)" --no-git-tag-version

            - name: Publish a package
              run: npm publish --tag dev
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
